version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qlcv-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - PORT=3000
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped
    networks:
      - qlcv-network

networks:
  qlcv-network:
    driver: bridge
