import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f9fafb',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: 12,
        fontSize: 16,
        color: '#6b7280',
    },
    projectSelector: {
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    selectorLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6b7280',
        marginBottom: 8,
        textTransform: 'uppercase',
    },
    projectButton: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#f3f4f6',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
    },
    projectButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
    },
    projectButtonIcon: {
        fontSize: 16,
        color: '#9ca3af',
    },
    projectChips: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    projectChip: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: '#f3f4f6',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    projectChipActive: {
        backgroundColor: '#f59e0b',
        borderColor: '#f59e0b',
    },
    projectChipText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#6b7280',
    },
    projectChipTextActive: {
        color: '#fff',
    },
    boardContainer: {
        paddingHorizontal: 16,
        paddingVertical: 16,
        flexDirection: 'row',
    },
    column: {
        width: 280,
        marginRight: 16,
        backgroundColor: '#fff',
        borderRadius: 12,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    columnHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 12,
    },
    columnTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#fff',
    },
    columnCount: {
        backgroundColor: 'rgba(255,255,255,0.3)',
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 12,
    },
    columnCountText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#fff',
    },
    columnContent: {
        flex: 1,
        padding: 12,
        maxHeight: 600,
    },
    taskCard: {
        backgroundColor: '#f8f9fa',
        borderRadius: 8,
        padding: 12,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    taskCardDragging: {
        opacity: 0.7,
        backgroundColor: '#fff',
        elevation: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    taskHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 8,
    },
    priorityDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginRight: 8,
        marginTop: 4,
    },
    taskTitle: {
        flex: 1,
        fontSize: 14,
        fontWeight: '600',
        color: '#1f2937',
        lineHeight: 18,
    },
    taskActionBtn: {
        padding: 4,
    },
    taskActionText: {
        fontSize: 16,
        color: '#6b7280',
        fontWeight: 'bold',
    },
    taskDesc: {
        fontSize: 12,
        color: '#6b7280',
        marginBottom: 8,
        lineHeight: 16,
    },
    assigneeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    assigneeAvatar: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#f59e0b',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 6,
    },
    assigneeInitial: {
        fontSize: 10,
        fontWeight: '700',
        color: '#fff',
    },
    assigneeName: {
        flex: 1,
        fontSize: 12,
        color: '#1f2937',
        fontWeight: '500',
    },
    dueDate: {
        fontSize: 11,
        color: '#6b7280',
    },
    taskPreview: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f3f4f6',
        padding: 12,
        borderRadius: 8,
        marginBottom: 16,
    },
    taskPreviewTitle: {
        flex: 1,
        fontSize: 14,
        fontWeight: '600',
        color: '#1f2937',
        marginLeft: 8,
    },
    emptyColumn: {
        paddingVertical: 24,
        alignItems: 'center',
    },
    emptyColumnText: {
        fontSize: 13,
        color: '#9ca3af',
        fontStyle: 'italic',
    },
    noProjectContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 32,
    },
    noProjectIcon: {
        fontSize: 64,
        marginBottom: 16,
    },
    noProjectTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1f2937',
        marginBottom: 8,
    },
    noProjectText: {
        fontSize: 14,
        color: '#6b7280',
        textAlign: 'center',
    },
} as any);

export const modalStyles = StyleSheet.create({
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 16,
    },
    modalContent: {
        width: '100%',
        maxWidth: 720,
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
    },
    modalTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1f2937',
        marginBottom: 12,
    },
    modalSubtitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#6b7280',
        marginBottom: 12,
    },
    statusOption: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 12,
        borderLeftWidth: 4,
        backgroundColor: '#f9fafb',
        borderRadius: 8,
        marginBottom: 8,
    },
    statusText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1f2937',
    },
    statusCount: {
        fontSize: 12,
        color: '#6b7280',
    },
    input: {
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: Platform.OS === 'ios' ? 12 : 8,
        marginBottom: 12,
        fontSize: 14,
        color: '#111827',
        backgroundColor: '#fff',
    },
    modalActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 12,
        marginTop: 16,
    },
    cancelButton: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 8,
        backgroundColor: '#f3f4f6',
    },
    cancelButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#6b7280',
    },
    submitButton: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 8,
        backgroundColor: '#f59e0b',
    },
    submitButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#fff',
    },
    submitButtonDisabled: {
        backgroundColor: '#d1d5db',
    },
});